create table Route (routeId integer generated by default as identity, distance double not null, destination_node varchar(255), origin_node varchar(255), primary key (routeId));
alter table Route add constraint FK_cpvn95tg093d1qajyl4i33f6v foreign key (destination_node) references Planet;
alter table Route add constraint FK_j26pa9u5uoat24f5fhlr17hl foreign key (origin_node) references Planet;